/**
 * Map ten bai tap → { gifUrl, description }
 * Video MP4 Cloudinary (EDB AscendAPI) cho FITNESS
 * Anh Unsplash cho MOOD/Yoga/Breathing/Stretch
 */

export const EXERCISE_GIF_MAP: Record<string, { gifUrl: string; description: string }> = {
  'Squat': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490675/healthhub/exercises/squat.mp4', description: 'The Bodyweight Standing Calf Raise is a simple yet effective exercise that targets the calf muscles, improving strength,' },
  'Push-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490680/healthhub/exercises/pushup.mp4', description: 'Push-ups are a versatile exercise that strengthens the chest, shoulders, triceps, and core muscles, making it beneficial' },
  'Plank': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490698/healthhub/exercises/plank.mp4', description: 'The Front Plank is a highly effective core-strengthening exercise that targets not only the abs but also the back and th' },
  'Jumping Jacks': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490744/healthhub/exercises/jumping-jacks.mp4', description: 'Jumping Jacks are a full-body workout that boosts cardiovascular health, improves flexibility, and enhances muscle stren' },
  'Glute Bridge': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490718/healthhub/exercises/glute-bridge.mp4', description: 'Hip Thrusts are a powerful exercise primarily targeting the glutes and hamstrings, helping to strengthen and tone these ' },
  'Pull-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490721/healthhub/exercises/pullup.mp4', description: 'The Pull-up exercise is a highly beneficial upper body workout that targets multiple muscle groups, including the back, ' },
  'Dips': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490730/healthhub/exercises/dips.mp4', description: 'Triceps Dips Floor is a bodyweight exercise that primarily targets the triceps, helping to build strength and muscle def' },
  'Diamond Push-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490684/healthhub/exercises/diamond-pushup.mp4', description: 'The Diamond Push-up is a challenging upper body exercise that primarily targets the triceps, chest, and shoulders, offer' },
  'Pike Push-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490688/healthhub/exercises/pike-pushup.mp4', description: 'The Decline Push-Up is a challenging upper body exercise that targets the chest, shoulders, triceps, and core muscles. I' },
  'Triceps Dip': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490730/healthhub/exercises/dips.mp4', description: 'Triceps Dips Floor is a bodyweight exercise that primarily targets the triceps, helping to build strength and muscle def' },
  'Burpee': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490738/healthhub/exercises/burpee.mp4', description: 'The Burpee is a full-body exercise that provides a high-intensity cardiovascular workout, strengthening the arms, chest,' },
  'High Knees': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490741/healthhub/exercises/high-knees.mp4', description: 'The Bodyweight Single Leg Deadlift is a versatile exercise that primarily targets the hamstrings, glutes, lower back, an' },
  'Jump Squat': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490750/healthhub/exercises/jump-squat.mp4', description: 'The Dumbbell Jumping Squat is a dynamic exercise that combines strength training with cardio, targeting the lower body m' },
  'Mountain Climber': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490747/healthhub/exercises/mountain-climber.mp4', description: 'The Bridge - Mountain Climber exercise is a dynamic workout that primarily targets your core, glutes, and lower body, wh' },
  'Box Jump': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490753/healthhub/exercises/box-jump.mp4', description: 'Jump Rope is a versatile, full-body workout that enhances cardiovascular health, improves coordination, and aids in weig' },
  'Bulgarian Split Squat': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490773/healthhub/exercises/bulgarian-squat.mp4', description: 'The Bulgarian Split Squat is a lower body strength exercise that targets the quads, glutes, and hamstrings, while also i' },
  'Romanian Deadlift': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490776/healthhub/exercises/romanian-deadlift.mp4', description: 'The Single Leg Bodyweight Deadlift with Arm and Leg Extended is a comprehensive exercise targeting the core, glutes, ham' },
  'Calf Raise': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490779/healthhub/exercises/calf-raise.mp4', description: 'The Bodyweight Standing Calf Raise is a simple yet effective exercise that targets the calf muscles, improving strength,' },
  'Wall Sit': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490781/healthhub/exercises/wall-sit.mp4', description: 'The Dumbbell Side Bend is a strength training exercise that primarily targets the obliques, helping to enhance core stab' },
  'Lunge': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490770/healthhub/exercises/lunge.mp4', description: 'The Bodyweight Rear Lunge is a versatile lower body exercise that strengthens your glutes, quads, and hamstrings while i' },
  'Crunch': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490781/healthhub/exercises/wall-sit.mp4', description: 'Crunch - Core exercise' },
  'Bicycle Crunch': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490779/healthhub/exercises/calf-raise.mp4', description: 'Bicycle Crunch - Core exercise' },
  'Leg Raise': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490776/healthhub/exercises/romanian-deadlift.mp4', description: 'Leg Raise - Core exercise' },
  'Russian Twist': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490773/healthhub/exercises/bulgarian-squat.mp4', description: 'Russian Twist - Core exercise' },
  'Plank Hold': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490698/healthhub/exercises/plank.mp4', description: 'The Front Plank is a highly effective core-strengthening exercise that targets not only the abs but also the back and th' },
  'Side Plank': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490715/healthhub/exercises/side-plank.mp4', description: 'The Elbow Up and Down Dynamic Plank is a challenging exercise that targets the core muscles, arms, and shoulders, enhanc' },
  'Wide-grip Pull-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490727/healthhub/exercises/wide-pullup.mp4', description: 'The Wide Grip Pull-Up is an upper-body exercise that primarily targets the latissimus dorsi, enhancing strength and impr' },
  'Close-grip Chin-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490724/healthhub/exercises/chin-up.mp4', description: 'The Chin-Up is a highly effective upper body exercise that primarily targets the muscles in your back, shoulders, and ar' },
  'Archer Push-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490692/healthhub/exercises/archer-pushup.mp4', description: 'The Elevated Push-Up is an advanced upper body exercise that targets the chest, shoulders, triceps, and core muscles, en' },
  'One-arm Push-up Prep': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490695/healthhub/exercises/one-arm-pushup.mp4', description: 'The Diamond Push-up is a challenging upper body exercise that primarily targets the triceps, chest, and shoulders, offer' },
  'Inverted Row': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490732/healthhub/exercises/inverted-row.mp4', description: 'The Self Assisted Inverted Pullover is a dynamic exercise that primarily targets the muscles of your back, shoulders, an' },
  'Depth Jump': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490750/healthhub/exercises/jump-squat.mp4', description: 'Depth Jump - Plyometric exercise' },
  'Broad Jump': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490759/healthhub/exercises/broad-jump.mp4', description: 'Body-Up is a comprehensive exercise that focuses on strengthening the upper body, including the arms, shoulders, and cor' },
  'Lateral Bound': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490761/healthhub/exercises/lateral-bound.mp4', description: 'The Bodyweight Single Leg Deadlift is a versatile exercise that primarily targets the hamstrings, glutes, lower back, an' },
  'Tuck Jump': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490755/healthhub/exercises/tuck-jump.mp4', description: 'Jump Rope is a versatile, full-body workout that enhances cardiovascular health, improves coordination, and aids in weig' },
  'Single-leg Hop': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490753/healthhub/exercises/box-jump.mp4', description: 'Single-leg Hop - Plyometric exercise' },
  'Jump Rope (mo phong)': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490744/healthhub/exercises/jumping-jacks.mp4', description: 'Jump Rope - Cardio exercise' },
  'Jump Rope (mô phỏng)': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490744/healthhub/exercises/jumping-jacks.mp4', description: 'Jump Rope - Cardio exercise' },
  'Squat Jump': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490750/healthhub/exercises/jump-squat.mp4', description: 'The Dumbbell Jumping Squat is a dynamic exercise that combines strength training with cardio, targeting the lower body m' },
  'Plank to Push-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490680/healthhub/exercises/pushup.mp4', description: 'Plank to Push-up - Full body exercise' },
  'Lateral Shuffle': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490767/healthhub/exercises/lateral-shuffle.mp4', description: 'The Bodyweight Single Leg Deadlift is a versatile exercise that primarily targets the hamstrings, glutes, lower back, an' },
  'Speed Skater': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490764/healthhub/exercises/speed-skater.mp4', description: 'The Back Pec Stretch is an effective exercise that primarily targets the chest muscles, promoting flexibility and reliev' },
  'Pseudo Planche Push-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490692/healthhub/exercises/archer-pushup.mp4', description: 'Pseudo Planche Push-up - Advanced calisthenics' },
  'L-sit Hold': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490698/healthhub/exercises/plank.mp4', description: 'L-sit Hold - Advanced calisthenics' },
  'Tuck Planche Hold': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490715/healthhub/exercises/side-plank.mp4', description: 'Tuck Planche Hold - Advanced calisthenics' },
  'Muscle-up Prep': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490735/healthhub/exercises/muscle-up.mp4', description: 'The Bodyweight Standing Calf Raise is a simple yet effective exercise that targets the calf muscles, improving strength,' },
  'Dragon Flag Negative': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490698/healthhub/exercises/plank.mp4', description: 'Dragon Flag Negative - Advanced core exercise' },
  'Desk Push-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490680/healthhub/exercises/pushup.mp4', description: 'Desk Push-up - Office exercise' },
  'Chair Squat': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490675/healthhub/exercises/squat.mp4', description: 'Chair Squat - Office exercise' },
  'Standing March': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490744/healthhub/exercises/jumping-jacks.mp4', description: 'Standing March - Office cardio' },
  'Torso Rotation': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Torso Rotation' },
  'Child\'s Pose': { gifUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80', description: 'Child\'s Pose' },
  'Cat-Cow Stretch': { gifUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80', description: 'Cat-Cow Stretch' },
  'Downward Dog': { gifUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80', description: 'Downward Dog' },
  'Warrior I': { gifUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80', description: 'Warrior I' },
  'Pigeon Pose': { gifUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80', description: 'Pigeon Pose' },
  'Happy Baby Pose': { gifUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80', description: 'Happy Baby Pose' },
  'Box Breathing 4-4-4-4': { gifUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&q=80', description: 'Box Breathing 4-4-4-4' },
  'Belly Breathing': { gifUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&q=80', description: 'Belly Breathing' },
  '4-7-8 Breathing': { gifUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&q=80', description: '4-7-8 Breathing' },
  'Alternate Nostril': { gifUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&q=80', description: 'Alternate Nostril' },
  'Body Scan Meditation': { gifUrl: 'https://images.unsplash.com/photo-1593811167562-9cef47bfc4d7?w=400&q=80', description: 'Body Scan Meditation' },
  'Gratitude Reflection': { gifUrl: 'https://images.unsplash.com/photo-1593811167562-9cef47bfc4d7?w=400&q=80', description: 'Gratitude Reflection' },
  'Supine Spinal Twist': { gifUrl: 'https://images.unsplash.com/photo-1593811167562-9cef47bfc4d7?w=400&q=80', description: 'Supine Spinal Twist' },
  'Legs Up The Wall': { gifUrl: 'https://images.unsplash.com/photo-1593811167562-9cef47bfc4d7?w=400&q=80', description: 'Legs Up The Wall' },
  'Progressive Muscle Relax': { gifUrl: 'https://images.unsplash.com/photo-1593811167562-9cef47bfc4d7?w=400&q=80', description: 'Progressive Muscle Relax' },
  'Mindful Walking': { gifUrl: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=400&q=80', description: 'Mindful Walking' },
  'Seated Forward Fold': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Seated Forward Fold' },
  'Hip Flexor Stretch': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Hip Flexor Stretch' },
  'Thoracic Spine Rotation': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Thoracic Spine Rotation' },
  'Neck Roll': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Neck Roll' },
  'Shoulder Cross Stretch': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Shoulder Cross Stretch' },
  'Quad Stretch': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Quad Stretch' },
  'Chin Tuck': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Chin Tuck' },
  'Shoulder Shrug': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Shoulder Shrug' },
  'Doorway Chest Stretch': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Doorway Chest Stretch' },
  'Levator Scapulae Stretch': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Levator Scapulae Stretch' },
  'Upper Trap Stretch': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Upper Trap Stretch' },
  'Seated Butterfly Stretch': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Seated Butterfly Stretch' },
  'Power Pose': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Power Pose' },
  // Extended fitness exercises
  'Superman': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490718/healthhub/exercises/glute-bridge.mp4', description: 'Superman - Back extension exercise targeting lower back, glutes and hamstrings' },
  'Hip Thrust': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490718/healthhub/exercises/glute-bridge.mp4', description: 'Hip Thrust - Powerful glute exercise for strength and muscle development' },
  'Step-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490770/healthhub/exercises/lunge.mp4', description: 'Step-up - Functional lower body exercise improving balance and leg strength' },
  'Reverse Lunge': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490770/healthhub/exercises/lunge.mp4', description: 'Reverse Lunge - Knee-friendly lunge variation targeting quads and glutes' },
  'Sumo Squat': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490675/healthhub/exercises/squat.mp4', description: 'Sumo Squat - Wide-stance squat targeting inner thighs and glutes' },
  'Knee Push-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490680/healthhub/exercises/pushup.mp4', description: 'Knee Push-up - Modified push-up for beginners building chest and arm strength' },
  'Triceps Kickback': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490730/healthhub/exercises/dips.mp4', description: 'Triceps Kickback - Isolation exercise targeting the triceps muscle' },
  'Shoulder Tap': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490698/healthhub/exercises/plank.mp4', description: 'Shoulder Tap Plank - Core stability exercise challenging anti-rotation strength' },
  'Dead Bug': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490698/healthhub/exercises/plank.mp4', description: 'Dead Bug - Core stabilization exercise improving coordination and spine control' },
  'Hollow Body Hold': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490698/healthhub/exercises/plank.mp4', description: 'Hollow Body Hold - Gymnastics core exercise building total body tension' },
  'V-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490776/healthhub/exercises/romanian-deadlift.mp4', description: 'V-up - Advanced core exercise combining leg raise and crunch' },
  'Flutter Kick': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490776/healthhub/exercises/romanian-deadlift.mp4', description: 'Flutter Kick - Lower abs exercise improving core endurance' },
  'Inchworm': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490747/healthhub/exercises/mountain-climber.mp4', description: 'Inchworm - Dynamic warm-up exercise stretching hamstrings and activating core' },
  'Squat to Stand': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490675/healthhub/exercises/squat.mp4', description: 'Squat to Stand - Mobility exercise warming up hips, hamstrings and ankles' },
  'Arm Circle': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Arm Circle - Shoulder warm-up improving joint mobility and blood flow' },
  'Leg Swing': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Leg Swing - Hip mobility drill preparing hips for exercise' },
  'World Greatest Stretch': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'World Greatest Stretch - Full body mobility exercise targeting multiple joints' },
  'T-spine Rotation': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'T-spine Rotation - Thoracic mobility drill improving upper back rotation' },
  'Lizard Stretch': { gifUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80', description: 'Lizard Stretch - Deep hip flexor and groin stretch' },
  'Figure Four Stretch': { gifUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80', description: 'Figure Four Stretch - Piriformis stretch reducing hip and lower back tension' },
  'Chest Opener': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Chest Opener - Posture correction stretch opening tight chest muscles' },
  'Eye of the Needle': { gifUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80', description: 'Eye of the Needle - Gentle shoulder and upper back stretch' },
  'Wrist Flexor Stretch': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Wrist Flexor Stretch - Forearm and wrist mobility for desk workers' },
  'Ankle Circle': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Ankle Circle - Lower leg mobility improving ankle stability' },
  'Calf Stretch': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Calf Stretch - Gastrocnemius stretch reducing tightness and injury risk' },
  'IT Band Stretch': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'IT Band Stretch - Lateral leg stretch relieving knee and hip discomfort' },
  'Standing Side Stretch': { gifUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80', description: 'Standing Side Stretch - Lateral flexion stretch for obliques and lats' },
  // MOOD extras
  'Loving Kindness Meditation': { gifUrl: 'https://images.unsplash.com/photo-1593811167562-9cef47bfc4d7?w=400&q=80', description: 'Loving Kindness Meditation - Compassion meditation improving emotional wellbeing' },
  'Visualization': { gifUrl: 'https://images.unsplash.com/photo-1593811167562-9cef47bfc4d7?w=400&q=80', description: 'Visualization - Mental rehearsal technique boosting confidence and focus' },
  'Journaling Prompt': { gifUrl: 'https://images.unsplash.com/photo-1593811167562-9cef47bfc4d7?w=400&q=80', description: 'Journaling Prompt - Reflective writing practice for emotional processing' },
  'Cold Water Splash': { gifUrl: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=400&q=80', description: 'Cold Water Splash - Quick energy reset activating the nervous system' },
  'Energizing Breath': { gifUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&q=80', description: 'Energizing Breath - Kapalabhati breathing technique for mental clarity' },
  'Coherent Breathing': { gifUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&q=80', description: 'Coherent Breathing - 5-second inhale/exhale cycle balancing autonomic nervous system' },
  'Wim Hof Breathing': { gifUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&q=80', description: 'Wim Hof Breathing - Powerful breath technique boosting energy and immune function' },
};
