/**
 * Map ten bai tap → { gifUrl, description }
 * Video MP4 Cloudinary (EDB AscendAPI) cho FITNESS
 * Anh Unsplash cho MOOD/Yoga/Breathing/Stretch
 */

export const EXERCISE_GIF_MAP: Record<string, { gifUrl: string; description: string }> = {
  'Squat': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490675/healthhub/exercises/squat.mp4', description: 'The Bodyweight Standing Calf Raise is a simple yet effective exercise that targets the calf muscles, improving strength,' },
  'Push-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490680/healthhub/exercises/pushup.mp4', description: 'Push-ups are a versatile exercise that strengthens the chest, shoulders, triceps, and core muscles, making it beneficial' },
  'Plank': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490698/healthhub/exercises/plank.mp4', description: 'The Front Plank is a highly effective core-strengthening exercise that targets not only the abs but also the back and th' },
  'Jumping Jacks': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490744/healthhub/exercises/jumping-jacks.mp4', description: 'Jumping Jacks are a full-body workout that boosts cardiovascular health, improves flexibility, and enhances muscle stren' },
  'Glute Bridge': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490718/healthhub/exercises/glute-bridge.mp4', description: 'Hip Thrusts are a powerful exercise primarily targeting the glutes and hamstrings, helping to strengthen and tone these ' },
  'Pull-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490721/healthhub/exercises/pullup.mp4', description: 'The Pull-up exercise is a highly beneficial upper body workout that targets multiple muscle groups, including the back, ' },
  'Dips': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490730/healthhub/exercises/dips.mp4', description: 'Triceps Dips Floor is a bodyweight exercise that primarily targets the triceps, helping to build strength and muscle def' },
  'Diamond Push-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490684/healthhub/exercises/diamond-pushup.mp4', description: 'The Diamond Push-up is a challenging upper body exercise that primarily targets the triceps, chest, and shoulders, offer' },
  'Pike Push-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490688/healthhub/exercises/pike-pushup.mp4', description: 'The Decline Push-Up is a challenging upper body exercise that targets the chest, shoulders, triceps, and core muscles. I' },
  'Triceps Dip': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490730/healthhub/exercises/dips.mp4', description: 'Triceps Dips Floor is a bodyweight exercise that primarily targets the triceps, helping to build strength and muscle def' },
  'Burpee': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490738/healthhub/exercises/burpee.mp4', description: 'The Burpee is a full-body exercise that provides a high-intensity cardiovascular workout, strengthening the arms, chest,' },
  'High Knees': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490741/healthhub/exercises/high-knees.mp4', description: 'The Bodyweight Single Leg Deadlift is a versatile exercise that primarily targets the hamstrings, glutes, lower back, an' },
  'Jump Squat': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490750/healthhub/exercises/jump-squat.mp4', description: 'The Dumbbell Jumping Squat is a dynamic exercise that combines strength training with cardio, targeting the lower body m' },
  'Mountain Climber': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490747/healthhub/exercises/mountain-climber.mp4', description: 'The Bridge - Mountain Climber exercise is a dynamic workout that primarily targets your core, glutes, and lower body, wh' },
  'Box Jump': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490753/healthhub/exercises/box-jump.mp4', description: 'Jump Rope is a versatile, full-body workout that enhances cardiovascular health, improves coordination, and aids in weig' },
  'Bulgarian Split Squat': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490773/healthhub/exercises/bulgarian-squat.mp4', description: 'The Bulgarian Split Squat is a lower body strength exercise that targets the quads, glutes, and hamstrings, while also i' },
  'Romanian Deadlift': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490776/healthhub/exercises/romanian-deadlift.mp4', description: 'The Single Leg Bodyweight Deadlift with Arm and Leg Extended is a comprehensive exercise targeting the core, glutes, ham' },
  'Calf Raise': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490779/healthhub/exercises/calf-raise.mp4', description: 'The Bodyweight Standing Calf Raise is a simple yet effective exercise that targets the calf muscles, improving strength,' },
  'Wall Sit': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490781/healthhub/exercises/wall-sit.mp4', description: 'The Dumbbell Side Bend is a strength training exercise that primarily targets the obliques, helping to enhance core stab' },
  'Lunge': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490770/healthhub/exercises/lunge.mp4', description: 'The Bodyweight Rear Lunge is a versatile lower body exercise that strengthens your glutes, quads, and hamstrings while i' },
  'Crunch': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490781/healthhub/exercises/wall-sit.mp4', description: 'Crunch - Core exercise' },
  'Bicycle Crunch': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490779/healthhub/exercises/calf-raise.mp4', description: 'Bicycle Crunch - Core exercise' },
  'Leg Raise': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490776/healthhub/exercises/romanian-deadlift.mp4', description: 'Leg Raise - Core exercise' },
  'Russian Twist': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490773/healthhub/exercises/bulgarian-squat.mp4', description: 'Russian Twist - Core exercise' },
  'Plank Hold': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490698/healthhub/exercises/plank.mp4', description: 'The Front Plank is a highly effective core-strengthening exercise that targets not only the abs but also the back and th' },
  'Side Plank': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490715/healthhub/exercises/side-plank.mp4', description: 'The Elbow Up and Down Dynamic Plank is a challenging exercise that targets the core muscles, arms, and shoulders, enhanc' },
  'Wide-grip Pull-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490727/healthhub/exercises/wide-pullup.mp4', description: 'The Wide Grip Pull-Up is an upper-body exercise that primarily targets the latissimus dorsi, enhancing strength and impr' },
  'Close-grip Chin-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490724/healthhub/exercises/chin-up.mp4', description: 'The Chin-Up is a highly effective upper body exercise that primarily targets the muscles in your back, shoulders, and ar' },
  'Archer Push-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490692/healthhub/exercises/archer-pushup.mp4', description: 'The Elevated Push-Up is an advanced upper body exercise that targets the chest, shoulders, triceps, and core muscles, en' },
  'One-arm Push-up Prep': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490695/healthhub/exercises/one-arm-pushup.mp4', description: 'The Diamond Push-up is a challenging upper body exercise that primarily targets the triceps, chest, and shoulders, offer' },
  'Inverted Row': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490732/healthhub/exercises/inverted-row.mp4', description: 'The Self Assisted Inverted Pullover is a dynamic exercise that primarily targets the muscles of your back, shoulders, an' },
  'Depth Jump': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490750/healthhub/exercises/jump-squat.mp4', description: 'Depth Jump - Plyometric exercise' },
  'Broad Jump': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490759/healthhub/exercises/broad-jump.mp4', description: 'Body-Up is a comprehensive exercise that focuses on strengthening the upper body, including the arms, shoulders, and cor' },
  'Lateral Bound': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490761/healthhub/exercises/lateral-bound.mp4', description: 'The Bodyweight Single Leg Deadlift is a versatile exercise that primarily targets the hamstrings, glutes, lower back, an' },
  'Tuck Jump': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490755/healthhub/exercises/tuck-jump.mp4', description: 'Jump Rope is a versatile, full-body workout that enhances cardiovascular health, improves coordination, and aids in weig' },
  'Single-leg Hop': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490753/healthhub/exercises/box-jump.mp4', description: 'Single-leg Hop - Plyometric exercise' },
  'Jump Rope (mo phong)': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490744/healthhub/exercises/jumping-jacks.mp4', description: 'Jump Rope - Cardio exercise' },
  'Jump Rope (mô phỏng)': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490744/healthhub/exercises/jumping-jacks.mp4', description: 'Jump Rope - Cardio exercise' },
  'Squat Jump': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490750/healthhub/exercises/jump-squat.mp4', description: 'The Dumbbell Jumping Squat is a dynamic exercise that combines strength training with cardio, targeting the lower body m' },
  'Plank to Push-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490680/healthhub/exercises/pushup.mp4', description: 'Plank to Push-up - Full body exercise' },
  'Lateral Shuffle': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490767/healthhub/exercises/lateral-shuffle.mp4', description: 'The Bodyweight Single Leg Deadlift is a versatile exercise that primarily targets the hamstrings, glutes, lower back, an' },
  'Speed Skater': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490764/healthhub/exercises/speed-skater.mp4', description: 'The Back Pec Stretch is an effective exercise that primarily targets the chest muscles, promoting flexibility and reliev' },
  'Pseudo Planche Push-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490692/healthhub/exercises/archer-pushup.mp4', description: 'Pseudo Planche Push-up - Advanced calisthenics' },
  'L-sit Hold': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490698/healthhub/exercises/plank.mp4', description: 'L-sit Hold - Advanced calisthenics' },
  'Tuck Planche Hold': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490715/healthhub/exercises/side-plank.mp4', description: 'Tuck Planche Hold - Advanced calisthenics' },
  'Muscle-up Prep': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490735/healthhub/exercises/muscle-up.mp4', description: 'The Bodyweight Standing Calf Raise is a simple yet effective exercise that targets the calf muscles, improving strength,' },
  'Dragon Flag Negative': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490698/healthhub/exercises/plank.mp4', description: 'Dragon Flag Negative - Advanced core exercise' },
  'Desk Push-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490680/healthhub/exercises/pushup.mp4', description: 'Desk Push-up - Office exercise' },
  'Chair Squat': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490675/healthhub/exercises/squat.mp4', description: 'Chair Squat - Office exercise' },
  'Standing March': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490744/healthhub/exercises/jumping-jacks.mp4', description: 'Standing March - Office cardio' },
  // ── Yoga / Stretch ──────────────────────────────────────────────────────────
  'Torso Rotation': { gifUrl: 'https://www.youtube.com/embed/qULTwquOuT4', description: 'Torso Rotation - Standing core mobility drill releasing tension in the spine and obliques' },
  "Child's Pose": { gifUrl: 'https://www.youtube.com/embed/eqVMAPM00DM', description: "Child's Pose - Restorative yoga pose gently stretching lower back, hips and thighs" },
  'Cat-Cow Stretch': { gifUrl: 'https://www.youtube.com/embed/kqnua4rHVVA', description: 'Cat-Cow Stretch - Spinal mobility flow synchronising breath and movement to release back tension' },
  'Downward Dog': { gifUrl: 'https://www.youtube.com/embed/EC7RGJ975iM', description: 'Downward Dog - Foundational yoga pose stretching hamstrings, calves, shoulders and spine' },
  'Warrior I': { gifUrl: 'https://www.youtube.com/embed/k_NhNMFBASU', description: 'Warrior I - Standing yoga pose building leg strength, hip flexibility and focus' },
  'Pigeon Pose': { gifUrl: 'https://www.youtube.com/embed/5_MpOCRfZfk', description: 'Pigeon Pose - Deep hip opener releasing piriformis and hip flexors, reducing lower back pain' },
  'Happy Baby Pose': { gifUrl: 'https://www.youtube.com/embed/q1kuGqMU43M', description: 'Happy Baby Pose - Gentle supine hip opener decompressing the lower spine and calming the nervous system' },
  'Supine Spinal Twist': { gifUrl: 'https://www.youtube.com/embed/OHGSQgMIDxY', description: 'Supine Spinal Twist - Restorative twist relieving back tension and improving spinal mobility' },
  'Legs Up The Wall': { gifUrl: 'https://www.youtube.com/embed/N-GBxkyA8SE', description: 'Legs Up The Wall - Passive inversion reducing leg fatigue and calming the nervous system' },
  'Seated Forward Fold': { gifUrl: 'https://www.youtube.com/embed/oXWFLCnqp1Y', description: 'Seated Forward Fold - Hamstring and lower back stretch promoting relaxation and flexibility' },
  'Lizard Stretch': { gifUrl: 'https://www.youtube.com/embed/s1WFzWHVfWo', description: 'Lizard Stretch - Deep hip flexor and groin stretch releasing tightness from sitting' },
  'Figure Four Stretch': { gifUrl: 'https://www.youtube.com/embed/pHyNDKK-4TE', description: 'Figure Four Stretch - Piriformis stretch reducing hip and sciatic tension' },
  'Chest Opener': { gifUrl: 'https://www.youtube.com/embed/UHr6FXBi7pw', description: 'Chest Opener - Posture correction stretch reversing rounded shoulders and tight chest' },
  'Eye of the Needle': { gifUrl: 'https://www.youtube.com/embed/lhMjODJl4bQ', description: 'Eye of the Needle - Gentle supine hip and shoulder stretch perfect before sleep' },
  'Seated Butterfly Stretch': { gifUrl: 'https://www.youtube.com/embed/j7MKvBMRffs', description: 'Seated Butterfly Stretch - Inner thigh and groin stretch improving hip flexibility' },
  'Standing Side Stretch': { gifUrl: 'https://www.youtube.com/embed/L-DN3fBG1bI', description: 'Standing Side Stretch - Lateral flexion releasing obliques, lats and intercostal muscles' },
  // ── Office / Mobility ────────────────────────────────────────────────────────
  'Hip Flexor Stretch': { gifUrl: 'https://www.youtube.com/embed/YQmpO3kNJoI', description: 'Hip Flexor Stretch - Lunge-based stretch correcting anterior pelvic tilt from prolonged sitting' },
  'Thoracic Spine Rotation': { gifUrl: 'https://www.youtube.com/embed/yCCN2JfEkzs', description: 'Thoracic Spine Rotation - Mid-back mobility drill reducing stiffness for desk workers' },
  'Neck Roll': { gifUrl: 'https://www.youtube.com/embed/V-PUiUbKBX8', description: 'Neck Roll - Gentle cervical mobility exercise releasing neck tension and headaches' },
  'Shoulder Cross Stretch': { gifUrl: 'https://www.youtube.com/embed/6AJkKuLmJiM', description: 'Shoulder Cross Stretch - Posterior deltoid stretch reducing shoulder impingement risk' },
  'Quad Stretch': { gifUrl: 'https://www.youtube.com/embed/Oxx_kXK6Iys', description: 'Quad Stretch - Standing quadriceps stretch restoring knee and hip extension range' },
  'Chin Tuck': { gifUrl: 'https://www.youtube.com/embed/wQylqaCl8Zo', description: 'Chin Tuck - Cervical retraction exercise correcting forward head posture at the desk' },
  'Shoulder Shrug': { gifUrl: 'https://www.youtube.com/embed/pqDr_VCTNXQ', description: 'Shoulder Shrug - Trapezius activation and release reducing upper back tension' },
  'Doorway Chest Stretch': { gifUrl: 'https://www.youtube.com/embed/dVCaJi4fBXU', description: 'Doorway Chest Stretch - Pectoral stretch opening rounded posture from computer use' },
  'Levator Scapulae Stretch': { gifUrl: 'https://www.youtube.com/embed/EiRC80FJbHU', description: 'Levator Scapulae Stretch - Targeted neck stretch releasing common tension point' },
  'Upper Trap Stretch': { gifUrl: 'https://www.youtube.com/embed/V-PUiUbKBX8', description: 'Upper Trap Stretch - Side-neck stretch reducing headaches and shoulder tightness' },
  'Power Pose': { gifUrl: 'https://www.youtube.com/embed/RVmkVPFn2_M', description: 'Power Pose - Expansive body posture boosting confidence and reducing cortisol before high-stakes tasks' },
  // ── Breathing ────────────────────────────────────────────────────────────────
  'Box Breathing 4-4-4-4': { gifUrl: 'https://www.youtube.com/embed/tEmt1Znux58', description: 'Box Breathing 4-4-4-4 - Navy SEAL breathing technique activating the parasympathetic system' },
  'Belly Breathing': { gifUrl: 'https://www.youtube.com/embed/kgTL5G1ibIo', description: 'Belly Breathing - Diaphragmatic breathing reducing cortisol and improving oxygen efficiency' },
  '4-7-8 Breathing': { gifUrl: 'https://www.youtube.com/embed/YRPh_GaiL8s', description: '4-7-8 Breathing - Dr Weil technique calming the nervous system and promoting sleep onset' },
  'Alternate Nostril': { gifUrl: 'https://www.youtube.com/embed/8VwufJrUhic', description: 'Alternate Nostril Breathing - Nadi Shodhana pranayama balancing left and right brain hemispheres' },
  'Coherent Breathing': { gifUrl: 'https://www.youtube.com/embed/8gEU5N9_u0k', description: 'Coherent Breathing - 5-second inhale/exhale cycle maximising heart rate variability and calm' },
  'Energizing Breath': { gifUrl: 'https://www.youtube.com/embed/YdSZMN_UsFk', description: 'Energizing Breath - Kapalabhati fire breath clearing mental fog and boosting alertness' },
  'Wim Hof Breathing': { gifUrl: 'https://www.youtube.com/embed/tybOi4hjZFQ', description: 'Wim Hof Breathing - Controlled hyperventilation technique boosting energy and immune resilience' },
  'Pursed Lip Breathing': { gifUrl: 'https://www.youtube.com/embed/ELMEnX3BGXI', description: 'Pursed Lip Breathing - Slow exhale technique calming panic and improving oxygen exchange' },
  'Humming Bee Breath': { gifUrl: 'https://www.youtube.com/embed/sGN3z2TIYoU', description: 'Humming Bee Breath (Bhramari) - Vibration-based pranayama instantly quieting mental chatter' },
  'Breath of Fire': { gifUrl: 'https://www.youtube.com/embed/fDZzWfVNqOA', description: 'Breath of Fire - Rapid rhythmic breathing clearing energy blockages and boosting vitality' },
  // ── Mindfulness / Meditation ─────────────────────────────────────────────────
  'Body Scan Meditation': { gifUrl: 'https://www.youtube.com/embed/QS2yDmWk0vs', description: 'Body Scan Meditation - Systematic awareness practice releasing physical tension and anxiety' },
  'Gratitude Reflection': { gifUrl: 'https://www.youtube.com/embed/WPPPFqsECz0', description: 'Gratitude Reflection - Evidence-based journaling practice rewiring the brain toward positivity' },
  'Progressive Muscle Relax': { gifUrl: 'https://www.youtube.com/embed/1nZEdqcGVzo', description: 'Progressive Muscle Relaxation - Jacobson technique systematically releasing tension from every muscle group' },
  'Mindful Walking': { gifUrl: 'https://www.youtube.com/embed/N5zNtB5dO1w', description: 'Mindful Walking - Meditative movement anchoring awareness to each step and breath' },
  'Loving Kindness Meditation': { gifUrl: 'https://www.youtube.com/embed/sz7cpV7ERsM', description: 'Loving Kindness Meditation - Metta practice cultivating compassion and reducing negative self-talk' },
  'Visualization': { gifUrl: 'https://www.youtube.com/embed/MIr3RsUWrdo', description: 'Visualization - Mental rehearsal technique used by elite athletes to prime performance and confidence' },
  'Journaling Prompt': { gifUrl: 'https://www.youtube.com/embed/f4Cv2Qm3y7k', description: 'Journaling Prompt - Guided reflective writing for emotional processing and self-awareness' },
  'Cold Water Splash': { gifUrl: 'https://www.youtube.com/embed/1kHVVgjWjEA', description: 'Cold Water Splash - Brief cold exposure activating the vagus nerve and resetting alertness' },
  // Extended fitness exercises
  'Superman': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490718/healthhub/exercises/glute-bridge.mp4', description: 'Superman - Back extension exercise targeting lower back, glutes and hamstrings' },
  'Hip Thrust': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490718/healthhub/exercises/glute-bridge.mp4', description: 'Hip Thrust - Powerful glute exercise for strength and muscle development' },
  'Step-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490770/healthhub/exercises/lunge.mp4', description: 'Step-up - Functional lower body exercise improving balance and leg strength' },
  'Reverse Lunge': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490770/healthhub/exercises/lunge.mp4', description: 'Reverse Lunge - Knee-friendly lunge variation targeting quads and glutes' },
  'Sumo Squat': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490675/healthhub/exercises/squat.mp4', description: 'Sumo Squat - Wide-stance squat targeting inner thighs and glutes' },
  'Knee Push-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490680/healthhub/exercises/pushup.mp4', description: 'Knee Push-up - Modified push-up for beginners building chest and arm strength' },
  'Triceps Kickback': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490730/healthhub/exercises/dips.mp4', description: 'Triceps Kickback - Isolation exercise targeting the triceps muscle' },
  'Shoulder Tap': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490698/healthhub/exercises/plank.mp4', description: 'Shoulder Tap Plank - Core stability exercise challenging anti-rotation strength' },
  'Dead Bug': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490698/healthhub/exercises/plank.mp4', description: 'Dead Bug - Core stabilization exercise improving coordination and spine control' },
  'Hollow Body Hold': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490698/healthhub/exercises/plank.mp4', description: 'Hollow Body Hold - Gymnastics core exercise building total body tension' },
  'V-up': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490776/healthhub/exercises/romanian-deadlift.mp4', description: 'V-up - Advanced core exercise combining leg raise and crunch' },
  'Flutter Kick': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490776/healthhub/exercises/romanian-deadlift.mp4', description: 'Flutter Kick - Lower abs exercise improving core endurance' },
  'Inchworm': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490747/healthhub/exercises/mountain-climber.mp4', description: 'Inchworm - Dynamic warm-up exercise stretching hamstrings and activating core' },
  'Squat to Stand': { gifUrl: 'https://res.cloudinary.com/dccqzdp3b/video/upload/v1782490675/healthhub/exercises/squat.mp4', description: 'Squat to Stand - Mobility exercise warming up hips, hamstrings and ankles' },
  'Arm Circle': { gifUrl: 'https://www.youtube.com/embed/qd2OCMN6_CQ', description: 'Arm Circle - Shoulder warm-up improving glenohumeral joint mobility and blood flow' },
  'Leg Swing': { gifUrl: 'https://www.youtube.com/embed/MWJHmVlf3Nk', description: 'Leg Swing - Dynamic hip mobility drill activating glutes and hip flexors pre-workout' },
  'World Greatest Stretch': { gifUrl: 'https://www.youtube.com/embed/eD3VeJgqTP8', description: 'World Greatest Stretch - Compound mobility exercise simultaneously targeting hip, thoracic and ankle flexibility' },
  'T-spine Rotation': { gifUrl: 'https://www.youtube.com/embed/yCCN2JfEkzs', description: 'T-spine Rotation - Thoracic mobility drill improving upper back rotation and shoulder function' },
  'Wrist Flexor Stretch': { gifUrl: 'https://www.youtube.com/embed/K9pJNHU78CE', description: 'Wrist Flexor Stretch - Forearm and wrist mobility essential for desk workers and push exercises' },
  'Ankle Circle': { gifUrl: 'https://www.youtube.com/embed/nkD6VN8kfGg', description: 'Ankle Circle - Lower leg mobility drill improving ankle stability and proprioception' },
  'Calf Stretch': { gifUrl: 'https://www.youtube.com/embed/X_6TmKHlbUE', description: 'Calf Stretch - Gastrocnemius stretch reducing achilles tension and injury risk' },
  'IT Band Stretch': { gifUrl: 'https://www.youtube.com/embed/K9-HMdMQHQA', description: 'IT Band Stretch - Lateral leg stretch relieving runner\'s knee and hip discomfort' },
  // ── Mindfulness extras ────────────────────────────────────────────────────────
  'Open Awareness Meditation': { gifUrl: 'https://www.youtube.com/embed/Jyy0ra2WcQQ', description: 'Open Awareness Meditation - Choiceless awareness practice expanding present-moment perception' },
  'Breath Counting': { gifUrl: 'https://www.youtube.com/embed/inpok4MKVLM', description: 'Breath Counting - Concentration meditation stabilising attention and reducing mind-wandering' },
  'Self-Compassion Break': { gifUrl: 'https://www.youtube.com/embed/11U0h0DPu7k', description: "Self-Compassion Break - Kristin Neff's 3-step practice softening self-criticism during difficult moments" },
  'Emotional Labelling': { gifUrl: 'https://www.youtube.com/embed/QS2yDmWk0vs', description: 'Emotional Labelling - Affect labelling technique reducing amygdala reactivity and emotional flooding' },
  'STOP Mindfulness': { gifUrl: 'https://www.youtube.com/embed/mxG9dDULe6U', description: 'STOP Practice - Stop, Take a breath, Observe, Proceed — 60-second stress interrupt for any situation' },
  'Grounding 5-4-3-2-1': { gifUrl: 'https://www.youtube.com/embed/30VMIEmA114', description: 'Grounding 5-4-3-2-1 - Sensory awareness technique anchoring to the present and relieving acute anxiety' },
  // ── New yoga poses ────────────────────────────────────────────────────────────
  'Bridge Pose': { gifUrl: 'https://www.youtube.com/embed/nOjBW_YpJ1I', description: 'Bridge Pose - Backbend strengthening glutes and hamstrings while opening the chest and hip flexors' },
  'Cobra Pose': { gifUrl: 'https://www.youtube.com/embed/JDcdhTuycOI', description: 'Cobra Pose - Gentle backbend stretching the chest, lungs and abdomen while toning the spine' },
  'Tree Pose': { gifUrl: 'https://www.youtube.com/embed/wdln9qWYloU', description: 'Tree Pose - Standing balance posture improving concentration, stability and postural awareness' },
  'Warrior II': { gifUrl: 'https://www.youtube.com/embed/4Ejz7IgODlU', description: 'Warrior II - Empowering standing pose building leg endurance, hip flexibility and mental focus' },
  'Triangle Pose': { gifUrl: 'https://www.youtube.com/embed/uZPsGDJQ4Fo', description: 'Triangle Pose - Full-body stretch improving lateral flexibility, balance and digestion' },
  'Seated Meditation': { gifUrl: 'https://www.youtube.com/embed/inpok4MKVLM', description: 'Seated Meditation - Classical mindfulness anchor for sustained focus and inner calm' },
  'Sun Salutation A': { gifUrl: 'https://www.youtube.com/embed/sF3iBBNbP7s', description: 'Sun Salutation A - Classic 12-pose vinyasa flow warming up the entire body and syncing breath with movement' },
  'Yin Hip Opener': { gifUrl: 'https://www.youtube.com/embed/sSUGFhzGfLM', description: 'Yin Hip Opener - Passive 3-minute hold releasing deep connective tissue in the hips and lower back' },
  'Restorative Savasana': { gifUrl: 'https://www.youtube.com/embed/1VYlOKUdylM', description: 'Restorative Savasana - Complete body relaxation integrating the benefits of practice and restoring the nervous system' },
  // ── Movement therapy ──────────────────────────────────────────────────────────
  'Shaking Therapy': { gifUrl: 'https://www.youtube.com/embed/FeUioDuJjFI', description: 'Shaking Therapy - Neurogenic tremor technique releasing stored stress and trauma from the body' },
  'Dance Freestyle': { gifUrl: 'https://www.youtube.com/embed/rFRZhSV8nFA', description: 'Dance Freestyle - Spontaneous movement releasing emotional tension and boosting dopamine' },
  'Qigong Flow': { gifUrl: 'https://www.youtube.com/embed/cwlvTcWR3Gs', description: 'Qigong Flow - Traditional Chinese energy cultivation combining slow movement, breath and intention' },
  'Tai Chi Basic Form': { gifUrl: 'https://www.youtube.com/embed/cEOS2zoyQw4', description: 'Tai Chi Basic Form - Slow meditative martial art improving balance, focus and stress resilience' },
  'Shoulder Rolls': { gifUrl: 'https://www.youtube.com/embed/pqDr_VCTNXQ', description: 'Shoulder Rolls - Simple tension-release movement for the upper back and trapezius' },
  'Hip Circle': { gifUrl: 'https://www.youtube.com/embed/MWJHmVlf3Nk', description: 'Hip Circle - Rotational hip mobility improving range of motion and releasing lower back tightness' },
  'Spinal Wave': { gifUrl: 'https://www.youtube.com/embed/kqnua4rHVVA', description: 'Spinal Wave - Sequential vertebral movement awakening proprioception along the entire spine' },
};
