version: "3.9"

services:
  # ---------------------- MYSQL ----------------------
  mysql:
    image: mysql:8
    container_name: mysql_healthhub
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: healthhub
      MYSQL_USER: healthuser
      MYSQL_PASSWORD: 123456
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - healthhub_network

  # ---------------------- MONGODB ----------------------
  mongo:
    image: mongo:7.0
    container_name: mongo_healthhub
    restart: always
    environment:
      MONGO_INITDB_DATABASE: healthhub
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - healthhub_network

  # ---------------------- BACKEND APP ----------------------
  # backend:
  #   build: .
  #   container_name: healthhub_backend
  #   restart: always
  #   command: npm run start:prod
  #   ports:
  #     - "4000:4000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #     mongo:
  #       condition: service_healthy
  #   networks:
  #     - healthhub_network
  #   volumes:
  #     - .:/app
  #   working_dir: /app

# ---------------------- VOLUMES ----------------------
volumes:
  mysql_data:
  mongo_data:

# ---------------------- NETWORK ----------------------
networks:
  healthhub_network:
    driver: bridge
